[project]
name = 'example'
version = '0.0.1'
releasenote = 'First release'
url = 'https://github.com/blok-ui/blok.bridge'
license = 'MIT'
contributors = ['wartman']
tags = ['markup', 'compiler']

[build.shared]
sources = [ 'example/src' ]
dependencies = ['breeze']
flags.js-es = "6"
flags.message-reporting = 'pretty'
flags.debug = true
flags.analyzer-optimize = true
flags.dce = "full"

[build.server]
main = 'Run'
dependencies = ['hxnodejs']
flags.breeze-output = 'styles-{{version}}'
target.type = 'js'
target.output = 'build.js'

[build.client]
main = 'ExampleIslands'
flags.breeze-output = 'none'
