[project]
name = 'example'
version = '0.0.1'
releasenote = 'First release'
url = 'https://github.com/blok-ui/blok.bridge'
license = 'MIT'
contributors = ['wartman']
tags = ['ui']

[shared]
sources = ['example/src']
dependencies = [{ name = 'breeze', version = '0.0.1' }]
flags.no-deprecation-warnings = true
flags.js-es = "6"
flags.message-reporting = 'pretty'
flags.debug = true
flags.analyzer-optimize = true
flags.dce = "full"

[server]
main = 'Run'
dependencies = [{ name = 'hxnodejs', version = '12.1.0' }]
flags.breeze-output = 'cwd:{{assets}}/styles-{{version}}'
target.type = 'js'
target.output = 'build.js'

[client]
main = 'ExampleIslands'
flags.breeze-output = 'none'
